#!/bin/bash

###############################################################################
# Spirit Tours - Email/SMTP Configuration Script
# Version: 1.0.0
# Descripción: Configuración completa de servidor SMTP propio con DKIM/SPF
###############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}ℹ ${NC}$@"; }
log_success() { echo -e "${GREEN}✓${NC} $@"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $@"; }
log_error() { echo -e "${RED}✗${NC} $@"; }

print_header() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  $1"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

check_root() {
    if [ "$EUID" -ne 0 ]; then 
        log_error "Este script debe ejecutarse como root o con sudo"
        exit 1
    fi
}

install_postfix() {
    print_header "Instalando Postfix"
    
    if command -v postfix &> /dev/null; then
        log_success "Postfix ya está instalado"
        postfix -v | head -1
        return 0
    fi
    
    log_info "Instalando Postfix..."
    
    # Pre-configure Postfix
    debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)"
    debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
    
    DEBIAN_FRONTEND=noninteractive apt-get install -y postfix
    
    log_success "Postfix instalado"
}

install_opendkim() {
    print_header "Instalando OpenDKIM"
    
    if command -v opendkim &> /dev/null; then
        log_success "OpenDKIM ya está instalado"
        return 0
    fi
    
    log_info "Instalando OpenDKIM..."
    apt-get install -y opendkim opendkim-tools
    
    log_success "OpenDKIM instalado"
}

configure_domain() {
    print_header "Configuración de Dominio"
    
    read -p "Ingrese su dominio (ej: spirittours.com): " DOMAIN
    
    if [ -z "$DOMAIN" ]; then
        log_error "Debe ingresar un dominio"
        exit 1
    fi
    
    log_info "Dominio configurado: $DOMAIN"
    
    read -p "Ingrese el email de envío (ej: noreply@$DOMAIN): " FROM_EMAIL
    
    if [ -z "$FROM_EMAIL" ]; then
        FROM_EMAIL="noreply@$DOMAIN"
    fi
    
    log_success "Email configurado: $FROM_EMAIL"
}

configure_postfix() {
    print_header "Configurando Postfix"
    
    local postfix_main="/etc/postfix/main.cf"
    
    log_info "Creando configuración de Postfix..."
    
    cat > "$postfix_main" << EOF
# Spirit Tours Postfix Configuration
# Generated by setup-email.sh

# Basic Configuration
myhostname = mail.$DOMAIN
mydomain = $DOMAIN
myorigin = \$mydomain
inet_interfaces = all
inet_protocols = ipv4

# Destination Configuration
mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +

# TLS Configuration
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:\${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache
smtpd_tls_security_level = may
smtp_tls_security_level = may

# SASL Authentication
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
broken_sasl_auth_clients = yes
smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain = \$myhostname

# Security Restrictions
smtpd_recipient_restrictions =
    permit_sasl_authenticated,
    permit_mynetworks,
    reject_unauth_destination,
    reject_invalid_hostname,
    reject_non_fqdn_hostname,
    reject_non_fqdn_sender,
    reject_non_fqdn_recipient,
    reject_unknown_sender_domain,
    reject_unknown_recipient_domain,
    reject_rbl_client zen.spamhaus.org,
    reject_rbl_client bl.spamcop.net,
    permit

smtpd_helo_restrictions =
    permit_mynetworks,
    reject_invalid_helo_hostname,
    reject_non_fqdn_helo_hostname,
    permit

# Message Size
message_size_limit = 52428800

# Milter Configuration (DKIM)
milter_protocol = 2
milter_default_action = accept
smtpd_milters = inet:localhost:8891
non_smtpd_milters = inet:localhost:8891

# Virtual Aliases
virtual_alias_maps = hash:/etc/postfix/virtual

# Header Checks
header_checks = regexp:/etc/postfix/header_checks
EOF
    
    log_success "Postfix configurado"
    
    # Create virtual aliases
    touch /etc/postfix/virtual
    postmap /etc/postfix/virtual
    
    # Create header checks
    cat > /etc/postfix/header_checks << EOF
/^Received:/    IGNORE
/^X-Originating-IP:/    IGNORE
EOF
    
    log_success "Archivos adicionales creados"
}

setup_dkim() {
    print_header "Configurando DKIM"
    
    local dkim_dir="/etc/opendkim"
    local keys_dir="$dkim_dir/keys/$DOMAIN"
    
    mkdir -p "$keys_dir"
    
    log_info "Generando claves DKIM para $DOMAIN..."
    
    cd "$keys_dir"
    opendkim-genkey -s default -d "$DOMAIN"
    chown opendkim:opendkim default.private
    chmod 600 default.private
    
    log_success "Claves DKIM generadas"
    
    # Configure OpenDKIM
    cat > /etc/opendkim.conf << EOF
# Spirit Tours OpenDKIM Configuration

Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes

Canonicalization        relaxed/simple
Mode                    sv
SubDomains              no

# Key Configuration
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts

# Socket
Socket                  inet:8891@localhost

# User/Group
UserID                  opendkim:opendkim
UMask                   002

# Other
PidFile                 /var/run/opendkim/opendkim.pid
EOF
    
    # KeyTable
    echo "default._domainkey.$DOMAIN $DOMAIN:default:$keys_dir/default.private" > /etc/opendkim/KeyTable
    
    # SigningTable
    echo "*@$DOMAIN default._domainkey.$DOMAIN" > /etc/opendkim/SigningTable
    
    # TrustedHosts
    cat > /etc/opendkim/TrustedHosts << EOF
127.0.0.1
localhost
.$DOMAIN
EOF
    
    log_success "OpenDKIM configurado"
    
    # Display DKIM public key
    print_header "Registro DNS DKIM"
    
    log_warning "IMPORTANTE: Agregue este registro TXT a su DNS:"
    echo ""
    echo "Nombre del registro: default._domainkey.$DOMAIN"
    echo "Tipo: TXT"
    echo "Valor:"
    cat "$keys_dir/default.txt"
    echo ""
    
    read -p "Presione Enter cuando haya agregado el registro DNS..."
}

configure_spf() {
    print_header "Configuración de SPF"
    
    local server_ip=$(curl -s ifconfig.me)
    
    log_info "IP del servidor: $server_ip"
    log_warning "Agregue este registro TXT a su DNS:"
    echo ""
    echo "Nombre del registro: $DOMAIN"
    echo "Tipo: TXT"
    echo "Valor: v=spf1 mx a ip4:$server_ip ~all"
    echo ""
    
    read -p "Presione Enter cuando haya agregado el registro SPF..."
}

configure_dmarc() {
    print_header "Configuración de DMARC"
    
    log_warning "Agregue este registro TXT a su DNS:"
    echo ""
    echo "Nombre del registro: _dmarc.$DOMAIN"
    echo "Tipo: TXT"
    echo "Valor: v=DMARC1; p=quarantine; rua=mailto:dmarc@$DOMAIN; pct=100"
    echo ""
    
    read -p "Presione Enter cuando haya agregado el registro DMARC..."
}

test_configuration() {
    print_header "Probando Configuración"
    
    log_info "Reiniciando servicios..."
    systemctl restart postfix
    systemctl restart opendkim
    
    sleep 2
    
    log_info "Verificando estado de servicios..."
    
    if systemctl is-active --quiet postfix; then
        log_success "Postfix está corriendo"
    else
        log_error "Postfix no está corriendo"
        systemctl status postfix
        exit 1
    fi
    
    if systemctl is-active --quiet opendkim; then
        log_success "OpenDKIM está corriendo"
    else
        log_error "OpenDKIM no está corriendo"
        systemctl status opendkim
        exit 1
    fi
    
    log_info "Probando envío de email de prueba..."
    
    echo "Este es un email de prueba desde Spirit Tours Email System" | \
        mail -s "Test Email" -a "From: $FROM_EMAIL" root
    
    log_success "Email de prueba enviado"
    log_info "Verifique /var/log/mail.log para confirmar el envío"
}

verify_dns_records() {
    print_header "Verificando Registros DNS"
    
    log_info "Verificando SPF..."
    if dig +short TXT "$DOMAIN" | grep -q "v=spf1"; then
        log_success "Registro SPF encontrado"
    else
        log_warning "Registro SPF no encontrado o aún no propagado"
    fi
    
    log_info "Verificando DKIM..."
    if dig +short TXT "default._domainkey.$DOMAIN" | grep -q "v=DKIM1"; then
        log_success "Registro DKIM encontrado"
    else
        log_warning "Registro DKIM no encontrado o aún no propagado"
    fi
    
    log_info "Verificando DMARC..."
    if dig +short TXT "_dmarc.$DOMAIN" | grep -q "v=DMARC1"; then
        log_success "Registro DMARC encontrado"
    else
        log_warning "Registro DMARC no encontrado o aún no propagado"
    fi
    
    log_info "Nota: La propagación DNS puede tomar hasta 48 horas"
}

display_summary() {
    print_header "Resumen de Configuración"
    
    echo ""
    echo "✅ Servidor SMTP configurado exitosamente"
    echo ""
    echo "📧 Información de Email:"
    echo "   • Dominio: $DOMAIN"
    echo "   • Email de envío: $FROM_EMAIL"
    echo "   • Servidor SMTP: mail.$DOMAIN"
    echo "   • Puerto: 587 (TLS)"
    echo ""
    echo "🔐 Seguridad:"
    echo "   • DKIM: Configurado"
    echo "   • SPF: Configurado"
    echo "   • DMARC: Configurado"
    echo ""
    echo "📝 Logs:"
    echo "   • Postfix: /var/log/mail.log"
    echo "   • OpenDKIM: /var/log/syslog"
    echo ""
    echo "🔍 Verificar configuración:"
    echo "   • https://mxtoolbox.com/SuperTool.aspx?action=dkim:default._domainkey.$DOMAIN"
    echo "   • https://mxtoolbox.com/spf.aspx?domain=$DOMAIN"
    echo "   • https://www.mail-tester.com/"
    echo ""
    echo "⚙️  Comandos útiles:"
    echo "   • Ver cola: mailq"
    echo "   • Limpiar cola: postsuper -d ALL"
    echo "   • Verificar logs: tail -f /var/log/mail.log"
    echo ""
    
    log_success "Configuración completada"
}

main() {
    cat << "EOF"
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║          📧  SPIRIT TOURS - EMAIL/SMTP SETUP  📧                    ║
║                                                                      ║
║            Configuración de Servidor Propio con DKIM/SPF             ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
EOF

    check_root
    install_postfix
    install_opendkim
    configure_domain
    configure_postfix
    setup_dkim
    configure_spf
    configure_dmarc
    test_configuration
    verify_dns_records
    display_summary
    
    echo ""
    log_success "🎉 Setup de Email completado exitosamente! 🎉"
    echo ""
}

trap 'log_error "Error en línea $LINENO. Setup fallido."; exit 1' ERR

main "$@"
